const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const projectRoot = path.resolve(__dirname, '..');
const sourcePath = path.join(projectRoot, 'shared/validation.js');
const copies = [
  path.join(projectRoot, 'miniprogram/utils/validation-shared.js'),
  path.join(projectRoot, 'cloudfunctions/records/validation-shared.js'),
];

const BANNER_LINES = 3; // 与 scripts/sync-shared.js 的 BANNER_LINES 保持一致

function stripBanner(content) {
  return content.split('\n').slice(BANNER_LINES).join('\n').trim();
}

test('generated validation copies match the source of truth', () => {
  const source = fs.readFileSync(sourcePath, 'utf8').trim();
  for (const copyPath of copies) {
    const copy = fs.readFileSync(copyPath, 'utf8');
    assert.match(copy, /^\/\/ GENERATED by scripts\/sync-shared\.js/, `${copyPath} 缺少生成标记`);
    assert.equal(stripBanner(copy), source, `${copyPath} 与 shared/validation.js 不一致，请运行 npm run sync`);
  }
});

test('client and cloud functions share identical record limits', () => {
  const client = require('../miniprogram/utils/validation-shared');
  const cloud = require('../cloudfunctions/records/validation-shared');

  assert.deepEqual(client.RECORD_LIMITS, cloud.RECORD_LIMITS);
  assert.equal(client.RECORD_LIMITS.sets.max, 100);
  assert.equal(client.RECORD_LIMITS.reps.max, 1000);
  assert.equal(client.RECORD_LIMITS.weight.max, 10000);
  assert.equal(client.RECORD_LIMITS.duration.max, 1440);
});

test('normalizeNumber enforces integer and range limits with matching messages', () => {
  const { normalizeNumber, RECORD_LIMITS } = require('../miniprogram/utils/validation-shared');

  assert.equal(normalizeNumber('4', RECORD_LIMITS.sets), 4);
  assert.equal(normalizeNumber(0, RECORD_LIMITS.weight), 0);
  assert.equal(normalizeNumber(2.5, RECORD_LIMITS.weight), 2.5);
  assert.throws(() => normalizeNumber(1.5, RECORD_LIMITS.sets), /组数应为 1-100 的整数/);
  assert.throws(() => normalizeNumber(101, RECORD_LIMITS.sets), /组数应为 1-100 的整数/);
  assert.throws(() => normalizeNumber(10001, RECORD_LIMITS.weight), /重量应为 0-10000/);
  assert.throws(() => normalizeNumber('abc', RECORD_LIMITS.sets), /组数必须是有效数字/);
});
