// scripts/sync-shared.js - 把 shared/ 下的唯一事实源同步为两端副本
//
// 副本文件带 GENERATED 标记，禁止手改；修改 shared/ 后运行 `npm run sync`。
// `npm run verify`（check 阶段）会先同步再跑测试，并断言副本与源一致。

const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');

const sources = [
  {
    file: 'shared/validation.js',
    targets: [
      'miniprogram/utils/validation-shared.js',
      'cloudfunctions/records/validation-shared.js',
    ],
  },
];

const BANNER = [
  '// GENERATED by scripts/sync-shared.js — DO NOT EDIT.',
  '// Source of truth: shared/validation.js. Run `npm run sync` to regenerate.',
  '',
  '',
].join('\n');

let synced = 0;
for (const { file, targets } of sources) {
  const content = fs.readFileSync(path.join(root, file), 'utf8');
  for (const target of targets) {
    fs.writeFileSync(path.join(root, target), BANNER + content);
    console.log(`Synced ${file} -> ${target}`);
    synced += 1;
  }
}
console.log(`Synced ${synced} shared file(s).`);
